Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 512
      Handler: helloworld.App
      CodeUri: /Users/joseong-ug/java-service/jobs-lambda/HelloWorldFunction
      Runtime: java11
      Architectures:
        - x86_64