Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: helloworld.App
      CodeUri: /Users/joseong-ug/reference-group/lambda-jobs01/HelloWorldFunction
      Runtime: java11
      Architectures:
        - x86_64